version: '3.9'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8084
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:5.6"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: springboot_db
      MYSQL_USER: bekaku
      MYSQL_PASSWORD: CH789162be
      MYSQL_ROOT_PASSWORD: CH789162be
volumes:
  mysql_data:





