# https://github.com/gothinkster/spring-boot-realworld-example-app
# https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/html/boot-features-external-config.html
# https://mkyong.com/spring-boot/spring-boot-yaml-example/
# https://www.baeldung.com/configuration-properties-in-spring-boot
environments:
  production: true
spring:
  profiles:
    active: dev
  #    active: prod
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true
  jpa:
    #    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    #    url: jdbc:mysql://${MYSQL_HOST:my.mysqlserver.com}:13537/springboot_bekaku?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springboot?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '@YOUR_REAL_MYSQL_PASSWORD'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #maximum number of milliseconds that a client will wait for a connection
      connection-timeout: 30000
      #minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-idle: 10
      maximum-pool-size: 20
      #idleTimeout: 600000
      idle-timeout: 600000
      # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      max-lifetime: 2000000
      keepalive-time: 30000
      autoCommit: true
    pool-prepared-statements: true
    max-open-prepared-statements: 250
  thymeleaf:
    cache: false
    #spring.freemarker.suffix=.html
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  h2:
    console:
      enabled:true
  devtools:
    add-properties: false
    restart:
      enabled: true
    livereload:
      enabled: true
  mail:
    host: smtp.mailtrap.io
    port: 25
    username:
    password:
    protocol: smtp
  mvc:
    #setting to default locale th_TH, en_US
    locale: th_TH
    #force locale resolver to spring boot reconized your settings
    locale-resolver: fixed

    # url pattern from resources/static can call with http://localhost:8080/content/about.html
    static-path-pattern: /content/**
  servlet:
    multipart:
      #upload files configurations
      enabled: true
      #It specifies the maximum size permitted for uploaded files. The default is 1MB.
      max-file-size: 10MB
      # It specifies the maximum size allowed for multipart/form-data requests. The default is 10MB.
      max-request-size: 15MB
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false
  tomcat:
    threads:
      max: 250

logging:
  pattern:
    rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i"
  file:
    #    name: D:/code/logs/MyApp.log
    path: /var/log/spring/
    max-history: 30
    total-size-cap: 10MB
    clean-history-on-start: true
  level:
    root: WARN
    web: DEBUG
    io.beka: DEBUG
    org:
      springframework: ERROR
      hibernate:
        SQL: ERROR
        type: ERROR

#spring.freemarker.suffix=.html
mybatis:
  typeAliasesPackage: io.beka.model
  # type-handlers-package: io.spring.infrastructure.mybatis
  # mybatis.mapper-locations=mapper/*.xml
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
app:
  url: https://www.mydomain.com
  port: 443
  test-prop: production mode
  version: 1.0.0
  cdn-path: file:////usr/edrdata/
  cdn-path-alias: cdn
  upload-image:
    limit-width: 960
    limit-height: 960
    create-thumbnail: true
    thumbnail-width: 160
    thumbnail-exname: '_thumb'

  loging:
    enable: true
  jwt:
    secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
    #default is 0 , if default set to 0 it automatic set exprires date in 1 day , you can set eg. 1 day to 86400, 2592000 = 30days
    session-time: 2592000
  defaults:
    image: https://static.productionready.io/images/smiley-cyrus.jpg
    role: 2
  #Object properties
  mail-config:
    host: smtp.mailtrap.io
    port: 25
    username:
    password:
    protocol: smtp
  #List properties
  default-recipients:
    - admin@mail.com
    - owner@mail.com
  #Map Properties
  additional-headers:
    redelivery: true
    secure: true
  #Object list
  menus:
    - title: Home
      name: Home
      path: /
    - title: About
      name: About
      path: /about


custom:
  config:
    file: Config Spring Startertemplate From PRODUCTION MODE (resources/application.yml)

